### ISSUE TITLE
회원가입 화면에서 PlaceHolder 미노출 

### ISSUE THREAD

**Issue by techinpark** [5boon/5boon-iOS#43]
## Issue content
- 회원가입화면 `TextField`의 `Placeholder` 이 미노출 되는 이슈가 있습니다.

## Expectation
- 노출되도록 수정합니다.

**Comment by techinpark** [comment]
기존에 사용중인 라이브러리 이슈인것으로 판단..

**Comment by 87kangsw** [comment]
라이브러리 문제가 아니라 Placeholder Color가 제대로 지정이 안되어 있었네용
Dark Mode가 아닐때는 노출이 되는군요

**Comment by techinpark** [comment]
@87kangsw 오 ㅋㅋ 다 다크모드 쓰고있어서 몰랐나보네요

**Comment by 87kangsw** [comment]
ㅋㅋㅋ
아직 다크모드 계획은 없는듯 하니..
Light로 바꾸려고요

**Comment by techinpark** [comment]
심플이즈베스트👍🏻

**Comment by 87kangsw** [comment]
요 [커밋](https://github.com/5boon/5boon-iOS/commit/f414446b7d67efaa646ff0a8e6f427a9980bbdc8)에서 처리하였으므로 close 할게욤
